name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.6'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyze
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test --reporter expanded

      - name: Build Web Release
        run: flutter build web --release
